//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./rpcService_types');
//HELPER FUNCTIONS AND STRUCTURES

SharedService_getRpc_args = function(args) {
};
SharedService_getRpc_args.prototype = {};
SharedService_getRpc_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SharedService_getRpc_args.prototype.write = function(output) {
  output.writeStructBegin('SharedService_getRpc_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SharedService_getRpc_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.Rpc(args.success);
    }
  }
};
SharedService_getRpc_result.prototype = {};
SharedService_getRpc_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Rpc();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SharedService_getRpc_result.prototype.write = function(output) {
  output.writeStructBegin('SharedService_getRpc_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SharedService_deal_args = function(args) {
  this.method = null;
  this.params = null;
  if (args) {
    if (args.method !== undefined && args.method !== null) {
      this.method = args.method;
    }
    if (args.params !== undefined && args.params !== null) {
      this.params = args.params;
    }
  }
};
SharedService_deal_args.prototype = {};
SharedService_deal_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.method = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.params = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SharedService_deal_args.prototype.write = function(output) {
  output.writeStructBegin('SharedService_deal_args');
  if (this.method !== null && this.method !== undefined) {
    output.writeFieldBegin('method', Thrift.Type.STRING, 1);
    output.writeString(this.method);
    output.writeFieldEnd();
  }
  if (this.params !== null && this.params !== undefined) {
    output.writeFieldBegin('params', Thrift.Type.STRING, 2);
    output.writeString(this.params);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SharedService_deal_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.Result(args.success);
    }
  }
};
SharedService_deal_result.prototype = {};
SharedService_deal_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Result();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SharedService_deal_result.prototype.write = function(output) {
  output.writeStructBegin('SharedService_deal_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SharedServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
SharedServiceClient.prototype = {};
SharedServiceClient.prototype.seqid = function() { return this._seqid; }
SharedServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
SharedServiceClient.prototype.getRpc = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getRpc();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getRpc();
  }
};

SharedServiceClient.prototype.send_getRpc = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getRpc', Thrift.MessageType.CALL, this.seqid());
  var args = new SharedService_getRpc_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

SharedServiceClient.prototype.recv_getRpc = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SharedService_getRpc_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getRpc failed: unknown result');
};
SharedServiceClient.prototype.deal = function(method, params, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_deal(method, params);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_deal(method, params);
  }
};

SharedServiceClient.prototype.send_deal = function(method, params) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('deal', Thrift.MessageType.CALL, this.seqid());
  var args = new SharedService_deal_args();
  args.method = method;
  args.params = params;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

SharedServiceClient.prototype.recv_deal = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SharedService_deal_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('deal failed: unknown result');
};
SharedServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
SharedServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

SharedServiceProcessor.prototype.process_getRpc = function(seqid, input, output) {
  var args = new SharedService_getRpc_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getRpc.length === 0) {
    Q.fcall(this._handler.getRpc)
      .then(function(result) {
        var result = new SharedService_getRpc_result({success: result});
        output.writeMessageBegin("getRpc", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getRpc", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getRpc(function (err, result) {
      if (err == null) {
        var result = new SharedService_getRpc_result((err != null ? err : {success: result}));
        output.writeMessageBegin("getRpc", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getRpc", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

SharedServiceProcessor.prototype.process_deal = function(seqid, input, output) {
  var args = new SharedService_deal_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.deal.length === 2) {
    Q.fcall(this._handler.deal, args.method, args.params)
      .then(function(result) {
        var result = new SharedService_deal_result({success: result});
        output.writeMessageBegin("deal", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("deal", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.deal(args.method, args.params, function (err, result) {
      if (err == null) {
        var result = new SharedService_deal_result((err != null ? err : {success: result}));
        output.writeMessageBegin("deal", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("deal", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

